"""
Core data contracts for the Autonomous Agent system.

These contracts define the "studs" (interfaces) between the system's "bricks" (modules).
Following the modular design philosophy: clear contracts enable independent module regeneration.
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, List, Optional


class StepStatus(Enum):
    """Execution status of a step"""

    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    SKIPPED = "skipped"


class ToolType(Enum):
    """Available tool types for execution"""

    CODE_EXEC = "code_exec"
    FILESYSTEM = "filesystem"
    RESEARCH = "research"
    BROWSER = "browser"  # Future: V1.0
    IMAGE_GEN = "image_gen"  # Future: V1.0


@dataclass
class TaskIntent:
    """User's task description and requirements"""

    goal: str
    context: dict[str, Any] = field(default_factory=dict)
    constraints: dict[str, Any] = field(default_factory=dict)
    user_id: str = "default_user"
    task_id: Optional[str] = None
    created_at: datetime = field(default_factory=datetime.utcnow)


@dataclass
class Step:
    """A single executable step in the execution plan"""

    step_id: str
    tool: ToolType
    inputs: dict[str, Any]
    expected_output: dict[str, Any]  # JSON schema
    timeout: int = 300  # seconds
    status: StepStatus = StepStatus.PENDING
    dependencies: List[str] = field(default_factory=list)  # step_ids this depends on
    created_at: datetime = field(default_factory=datetime.utcnow)


@dataclass
class ExecutionPlan:
    """Complete execution plan generated by Planner"""

    task_id: str
    steps: List[Step]
    success_criteria: dict[str, Any]
    estimated_duration: int = 0  # seconds
    created_at: datetime = field(default_factory=datetime.utcnow)
    created_by: str = "planner"

    def get_step(self, step_id: str) -> Optional[Step]:
        """Retrieve a specific step by ID"""
        for step in self.steps:
            if step.step_id == step_id:
                return step
        return None

    def get_ready_steps(self) -> List[Step]:
        """Get steps that are ready to execute (all dependencies met)"""
        ready = []
        completed_ids = {s.step_id for s in self.steps if s.status == StepStatus.COMPLETED}

        for step in self.steps:
            if step.status == StepStatus.PENDING:
                deps_met = all(dep_id in completed_ids for dep_id in step.dependencies)
                if deps_met:
                    ready.append(step)

        return ready


@dataclass
class Artifact:
    """Output generated by a step execution"""

    artifact_id: str
    content: Any
    content_type: str  # "code", "text", "json", "file_path", etc.
    schema_version: str = "1.0"
    created_by: str = ""  # step_id
    metadata: dict[str, Any] = field(default_factory=dict)
    created_at: datetime = field(default_factory=datetime.utcnow)
    provenance: List[str] = field(default_factory=list)  # chain of step_ids


@dataclass
class Check:
    """Individual verification check result"""

    check_type: str  # "logical", "factual", "structural", "assumption"
    passed: bool
    details: str
    confidence: float = 1.0  # 0.0 to 1.0
    evidence: dict[str, Any] = field(default_factory=dict)


@dataclass
class Issue:
    """Problem identified during verification"""

    severity: str  # "critical", "major", "minor", "warning"
    description: str
    step_id: Optional[str] = None
    artifact_id: Optional[str] = None
    recommendation: str = ""


@dataclass
class ValidationResult:
    """Result of Verifier's independent validation"""

    passed: bool
    checks: List[Check]
    issues: List[Issue]
    confidence: float  # Overall confidence (0.0 to 1.0)
    verified_at: datetime = field(default_factory=datetime.utcnow)
    verified_by: str = "verifier"

    @property
    def critical_issues(self) -> List[Issue]:
        """Get only critical issues"""
        return [i for i in self.issues if i.severity == "critical"]

    @property
    def has_critical_issues(self) -> bool:
        """Check if there are any critical issues"""
        return len(self.critical_issues) > 0


@dataclass
class TaskResult:
    """Final result delivered to user"""

    task_id: str
    success: bool
    artifacts: List[Artifact]
    validation: ValidationResult
    execution_time: float  # seconds
    plan: ExecutionPlan
    completed_at: datetime = field(default_factory=datetime.utcnow)
    error: Optional[str] = None
